### ISSUE TITLE
Error message is not captured from ava tap report

### ISSUE THREAD

**Issue by ishymko** [dhershman1/tap-junit#34]
**Describe the bug**
Error message in tap report from `ava` is not captured in JUnit report.

**To Reproduce**
1. See the repo https://github.com/vanashimko/ava-tap-junit-reproduce
2. `npm run test`
3. Observe `tap.txt`:
```
TAP version 13
not ok 1 - 2+2=4
  ---
    name: AssertionError
    assertion: is
    values:
      'Difference:': |-
        - 4
        + 5
    at: 'test.js:4:4'
  ...

1..1
# tests 1
# pass 0
# fail 1
```
4. Observe generated tap.xml
```
<?xml version="1.0"?>
<testsuites tests="1" name="Tap-Junit" failures="1">
  <testsuite name="Tap-Junit-Suite" tests="1" skipped="0" failures="1">
    <testcase name="2+2=4" id="1">
      <failure type="fail"> </failure>
    </testcase>
  </testsuite>
</testsuites>
```

**Expected behavior**
Error message from tap report is saved to JUnit report.

**Desktop (please complete the following information):**
 - OS: Windows and Linux
 - Browser: N/A (nodejs 14.15.4 LTS)

**Comment by dhershman1** [comment]
Hmm, thank you for the report. If building this module has taught me anything, it's that it seems like most testing suites use TAP in different ways lol.

**Comment by dhershman1** [comment]
@vanashimko question, does this need to be formatted in a specific way? I am basically just going to build a function that takes in the diag object I get and print it out. That way everyone just gets the diag and no special naming is needed.

But I don't know if formatting is important here or not, or if you literally just want the error so you can see whats up.

EDIT: Added the breaking tag because this is probably going to change the output for the xml, which means a major version bump, woooo

**Comment by ishymko** [comment]
@dhershman1 thanks for quick response!

>if you literally just want the error so you can see whats up

Yeah that's the case, formatting is not important for me.

**Comment by dhershman1** [comment]
Okay, I think I kept the damage to a minimum, do you mind trying v4.2.0 of tap-junit and seeing if that works for you

EDIT: Please re open this issue if the problem persists with other outputs

**Comment by ishymko** [comment]
Thanks @dhershman1, all good now, output is captured!
